frontend/controllers/CartController.php
<?php
namespace frontend\controllers;

use common\components\AjaxFilter;
use common\models\Item;
use common\models\ItemImage;
use frontend\components\Controller;
use Yii;
use yii\base\InvalidParamException;
use yii\db\Expression;
use yii\helpers\Url;
use yii\web\HttpException;

/**
 * Class CartController
 * @package frontend\controllers
 */
class CartController extends Controller
{
    /**
     * @return array
     */
    public function behaviors()
    {
        return [
            'ajax' => [
                'class' => AjaxFilter::className(),
                'only' => [
                    'buy',
                    'change-count',
                    'del-checked',
                    'update'
                ],
            ],
        ];
    }

    /**
     * @return string
     * @throws HttpException
     */
    public function actionIndex()
    {
        $positions = Yii::$app->cart->getPositions();
        $randomItems = Item::find()
            ->joinWith('defaultImage')
            ->where(['IS NOT', ItemImage::tableName() . '.id', null])
            ->orderBy(new Expression('RAND()'))
            ->limit(5)
            ->all();

        return $this->render('index', [
            'positions' => $positions,
            'randomItems' => $randomItems,
        ]);
    }

    /**
     * @return bool
     */
    public function actionBuy()
    {
        $post = Yii::$app->request->post();
        $model = $this->findItem($post['itemId']);
        $count = 1;

        if (!empty($post['count'])) {
            $count = $post['count'];
        }

        Yii::$app->cart->put($model, $count);

        return true;
    }

    /**
     * @param $id
     * @return bool
     */
    public function actionDelete($id)
    {
        $model = $this->findItem($id);
        Yii::$app->cart->remove($model);

        $this->redirect(Url::toRoute('cart/index'));
    }

    /**
     * @return array
     */
    public function actionChangeCount()
    {
        $post = Yii::$app->request->post();

        if (!empty($post['itemId']) && !empty($post['count'])) {
            $model = $this->findItem($post['itemId']);
            Yii::$app->cart->update($model, $post['count']);

            return [
                'cost' => Yii::$app->cart->getPositionById($model->id)->getCost(),
                'totalCost' => Yii::$app->cart->getCost()
            ];
        }
    }

    /**
     * @return array
     */
    public function actionDelChecked()
    {
        $post = Yii::$app->request->post();

        if (!empty($post['ids'])) {
            foreach ($post['ids'] as $id) {
                $model = $this->findItem($id);

                if ($model) {
                    Yii::$app->cart->removeById($model->id);
                }
            }

            return [
                'totalCost' => Yii::$app->cart->getCost(),
                'totalCount' => Yii::$app->cart->getCount(),
            ];
        }
    }

    /**
     * @return array
     */
    public function actionUpdate()
    {
        return [
            'totalCost' => Yii::$app->cart->getCost(),
            'totalCount' => Yii::$app->cart->getCount(),
        ];
    }

    /**
     * @param $id
     * @return Item|InvalidParamException
     */
    public function findItem($id)
    {
        $model = Item::findOne($id);

        if (!$model) {
            throw new InvalidParamException(Yii::t('common', 'Товар не найден'));
        }

        return $model;
    }

}

frontend/controllers/OrderController.php
<?php
namespace frontend\controllers;

use common\models\Options;
use common\models\Order;
use common\models\OrderItem;
use frontend\components\Controller;
use Yii;
use yii\helpers\Url;
use yii\web\HttpException;

/**
 * Class OrderController
 * @package frontend\controllers
 */
class OrderController extends Controller
{
    /**
     * @return string
     * @throws HttpException
     */
    public function actionIndex()
    {
        $positions = Yii::$app->cart->getPositions();

        if (!$positions) {
            throw new HttpException(404, Yii::t('common', 'Невозможно выполнить действие'));
        }

        $order = new Order();
        $post = Yii::$app->request->post();

        if ($post) {
            $order->load($post);
            $order->hash_session = Yii::$app->cart->session->id;

            if ($order->save()) {
                foreach ($positions as $position) {
                    $itemOrder = new OrderItem();
                    $itemOrder->order_id = $order->id;
                    $itemOrder->item_id = $position->id;
                    $itemOrder->quantity = $position->quantity;
                    $itemOrder->cost = $position->price;
                    $itemOrder->save();
                }

                $this->redirect(Url::toRoute('/order/final'));
            } else {
                Yii::$app->notifier->addNotifierErrorByModel($order);
            }
        };

        return $this->render('index', [
            'order' => $order
        ]);
    }

    /**
     * @return string|\yii\web\Response
     */
    public function actionFinal()
    {
        $sessionId = Yii::$app->cart->session->id;

        $order = Order::find()
            ->joinWith('orderItems')
            ->where(['hash_session' => $sessionId])
            ->one();

        if ($order) {
            Yii::$app->cart->removeAll();

            $order->hash_session = null;
            $order->save();

            $this->sendMail($order);

            return $this->render('final', [
                'order' => $order
            ]);
        } else {
            return $this->redirect('/');
        }
    }

    /**
     * @param $order
     * @return bool
     */
    public function sendMail($order)
    {
        try {
            Yii::$app->mailer->compose('@common/mail/newOrder', [
                'order' => $order
            ])
                ->setFrom(Yii::$app->params['noReplyEmail'])
                ->setTo(Options::getEmails())
                ->setSubject('Новый заказ')
                ->send();

            return true;
        } catch (\Exception $e) {
            return false;
        }
    }
}

frontend/views/cart/index.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;

$this->title = Yii::t('common', Yii::t('common', 'Корзина'));
$this->params['breadcrumbs'][] = ['label' => $this->title];

/** @var \common\models\Item[] $positions */
/** @var \common\models\Item[] $randomItems */
?>

<div class="p-cart">
    <?php if ($positions): ?>
        <?php Pjax::begin([
            'id' => 'cart-positions-pjax'
        ]) ?>
        <table class="cart">
            <tbody>
            <?php foreach ($positions as $key => $position): ?>
                <tr data-item-id="<?= $position->id ?>">
                    <td class="check">
                        <input type="checkbox" data-item-id="<?= $position->id ?>" id="check-cart-<?= $position->id ?>">
                        <label for="check-cart-<?= $position->id ?>"></label>
                    </td>
                    <td class="img">
                        <?= Html::img(Url::toRoute('/image/' . (!is_null($position->defaultImage) ? $position->defaultImage->size_medium : "index"))) ?>
                    </td>
                    <td>
                        <p class="name"><?= $position->name ?></p>
                        <p class="article"><?= $position->code ? 'арт. ' . $position->code : "" ?></p>
                    </td>
                    <td class="count">
                        <span>Кол-во: </span>
                        <div class="number-input">
                            <input type="number" class="number-item" readonly="readonly"
                                   value="<?= Yii::$app->cart->getPositionById($position->id)->quantity ?>">
                            <a href="#" class="up-num"></a>
                            <a href="#" class="down-num"></a>
                        </div>
                    </td>
                    <td class="old-cost"><?= $position->discount ? $position->cost + ($position->cost * ($position->discount / 100)) . 'р.' : "" ?>
                    </td>
                    <td class="cost"><?= $position->cost * Yii::$app->cart->getPositionById($position->id)->quantity ?>
                        р.
                    </td>
                    <td class="discount"><?= $position->discount ? $position->discount . '%' : "" ?></td>
                    <td class="remove">
                        <?= Html::a('', Url::toRoute('/cart/delete/' . $position->id), ['class' => 'del-pos']) ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <?php Pjax::end() ?>
        <div class="bottom-cart">
            <?= Html::a(Yii::t('common', 'Удалить выделенное'), '#', ['class' => 'del-checked']) ?>
            <?= Html::a(Yii::t('common', 'Оформить заказ'), Url::toRoute('/order/index'), [
                'class' => 'btn-customer new-order',
                'onClick' => 'yaCounter43756344.reachGoal ("order"); return true;',
            ]) ?>

            <p class="total">Общая сумма: <span class="sum"><?= Yii::$app->cart->getCost() ?> <span>р.</span></span></p>
        </div>
        <div class="assoc-goods">
            <h3 class="title">С этими товарами покупают</h3>
            <?php foreach ($randomItems as $randomItem): ?>
                <div class="item">
                    <div class="photo">
                        <?= Html::img(Url::toRoute('/image/' . (!is_null($randomItem->defaultImage) ? $randomItem->defaultImage->size_medium : ""), true)) ?>
                        <div class="block-buttons">
                            <?= Html::a('', Url::toRoute('/item/' . $randomItem->id), ['class' => 'view']) ?>
                            <?= Html::a('', Url::toRoute('#'), ['data-item-id' => $randomItem->id, 'class' => 'buy']) ?>
                        </div>
                    </div>
                    <p class="desc"><?= $randomItem->description ?></p>
                    <p class="cost"><?= $randomItem->cost ?> <span>р</span><span
                            class="discount"><?= $randomItem->discount ? '-' . $randomItem->discount . '%' : "" ?></span>
                    </p>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <p class="no-goods-in-cart"
       style="display:<?= $positions ? "none" : "block" ?>"><?= Yii::t('common', 'Нет добавленных товаров') ?></p>
</div>